version: '3'
services:
  app:
    container_name: shopping-cart
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: db-shopping-cart
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data